scrape_configs:
  - job_name: 'airflow_service'
    static_configs:
      - targets: ['airflow:8080']

  - job_name: 'data_collector_service'
    static_configs:
      - targets: ['data-collector:8000']

  - job_name: 'data_processor_service'
    static_configs:
      - targets: ['data-processor:8001']

  - job_name: 'database_writer_service'
    static_configs:
      - targets: ['database-writer:8002']

  - job_name: 'file_writer_service'
    static_configs:
      - targets: ['file-writer:8003']

  - job_name: 'monitoring_service'
    static_configs:
      - targets: ['monitoring:8004']

  - job_name: 'observability_service'
    static_configs:
      - targets: ['observability:8005']

  - job_name: 'data_api_service'
    static_configs:
      - targets: ['data-api-service:8006']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
