apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: database-writer-servicemonitor
  labels:
    release: kube-prometheus-stack-prometheus
 
spec:
  jobLabel: io.kompose.service
  selector:
    matchLabels:
      io.kompose.service: database-writer
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics/
      interval: 15s
