apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: file-writer-claim0
  name: file-writer-claim0
 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
