---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
data:
  init-db.sql: |
    CREATE TABLE IF NOT EXISTS "StockData" (
        "StockName" VARCHAR(10),
        "Date" DATE,
        "Open" DOUBLE PRECISION,
        "High" DOUBLE PRECISION,
        "Low" DOUBLE PRECISION,
        "Close" DOUBLE PRECISION,
        "Volume" BIGINT,
        PRIMARY KEY ("StockName", "Date")
    );

    CREATE TABLE IF NOT EXISTS "call_options" (
        "contractSymbol" VARCHAR(50) NOT NULL,
        "lastTradeDate" TIMESTAMP NOT NULL,
        "expirationDate" DATE NOT NULL,
        "strike" DECIMAL(10,2) NOT NULL,
        "lastPrice" DECIMAL(10,2),
        "bid" DECIMAL(10,2),
        "ask" DECIMAL(10,2),
        "change" DECIMAL(10,2),
        "percentChange" DECIMAL(10,4),
        "volume" BIGINT,
        "openInterest" BIGINT,
        "impliedVolatility" DECIMAL(10,4),
        "inTheMoney" BOOLEAN,
        "contractSize" VARCHAR(20) NOT NULL,
        "currency" VARCHAR(3) NOT NULL,
        "StockName" VARCHAR(10) NOT NULL,
        "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY ("contractSymbol", "lastTradeDate", "StockName", "expirationDate")
    );

    CREATE TABLE IF NOT EXISTS "put_options" (
        "contractSymbol" VARCHAR(50) NOT NULL,
        "lastTradeDate" TIMESTAMP NOT NULL,
        "expirationDate" DATE NOT NULL,
        "strike" DECIMAL(10,2) NOT NULL,
        "lastPrice" DECIMAL(10,2),
        "bid" DECIMAL(10,2),
        "ask" DECIMAL(10,2),
        "change" DECIMAL(10,2),
        "percentChange" DECIMAL(10,4),
        "volume" BIGINT,
        "openInterest" BIGINT,
        "impliedVolatility" DECIMAL(10,4),
        "inTheMoney" BOOLEAN,
        "contractSize" VARCHAR(20) NOT NULL,
        "currency" VARCHAR(3) NOT NULL,
        "StockName" VARCHAR(10) NOT NULL,
        "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY ("contractSymbol", "lastTradeDate", "StockName", "expirationDate")
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chown 999:999 /var/lib/postgresql/data && chmod 700 /var/lib/postgresql/data"]
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "sa"
            - name: POSTGRES_PASSWORD
              value: "Passw0rd!"
            - name: POSTGRES_DB
              value: "us_stock_options_db"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d/init-db.sql
              subPath: init-db.sql
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-db
          configMap:
            name: postgres-initdb-config