apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: data-api-servicemonitor
  labels:
    release: kube-prometheus-stack-prometheus
 
spec:
  jobLabel: io.kompose.service
  selector:
    matchLabels:
      io.kompose.service: data-api-service
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
