apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: file-writer-claim0
  name: file-writer-claim0
 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s-manifests
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: file-writer
  name: file-writer
 
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: file-writer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --out k8s-manifests
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: file-writer
    spec:
      # imagePullSecrets:
      #   - name: dockerhub-secret
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              value:
            - name: AWS_SECRET_ACCESS_KEY
              value:
            - name: AZURE_SQL_CONNECTION_STRING
              value: Driver={ODBC Driver 18 for SQL Server};Server=tcp:dash-gtd02.database.windows.net,1433;Database=us_stock_options_db;Uid=dash_gtd;Pwd=wearethebest@69;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;
            - name: S3_BUCKET_NAME
              value: dash-gtd-us-east-1-processed-data
          image: hdm08/file_writer_service_arm10:latest
          name: file-writer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
              protocol: TCP
          volumeMounts:
            - mountPath: /app/daily_exports
              name: file-writer-claim0
      restartPolicy: Always
      volumes:
        - name: file-writer-claim0
          persistentVolumeClaim:
            claimName: file-writer-claim0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s-manifests
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: file-writer
  name: file-writer
 
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8003
      targetPort: 8003
  selector:
    io.kompose.service: file-writer